import pptxgen from "pptxgenjs";
import path from "path";
import { fileURLToPath } from "url";
import { groqLLM } from "../../config/llmModels.js";
import { SystemMessage, HumanMessage, AIMessage } from "@langchain/core/messages";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const pptNode = async (state) => {
  const lastMessage = state.messages[state.messages.length - 1];
  
  const systemPrompt = new SystemMessage(`
    You are an expert presentation generator for Sumeet AI.
    Create an outline for a 3-slide presentation based on the user's request.
    Return EXACTLY a JSON array of 3 objects, each with 'title' and 'content' fields.
    Example: [{"title": "Intro", "content": "Welcome..."}, ...]
  `);

  let slidesData = [];
  try {
    const res = await groqLLM.invoke([systemPrompt, new HumanMessage(lastMessage.content)]);
    const match = res.content.match(/\[([\s\S]*?)\]/);
    if (match) slidesData = JSON.parse(`[${match[1]}]`);
  } catch (e) {
    console.error("PPT JSON parse failed", e);
    slidesData = [{ title: "Presentation", content: "Generated by Sumeet AI." }];
  }

  const fileName = `presentation_${Date.now()}.pptx`;
  const pptPath = path.join(__dirname, "../../public/uploads", fileName);
  
  const pres = new pptxgen();
  slidesData.forEach(slideData => {
    const slide = pres.addSlide();
    slide.addText(slideData.title, { x: 1, y: 1, fontSize: 24, align: "center" });
    slide.addText(slideData.content, { x: 1, y: 2.5, fontSize: 16, align: "center" });
  });
  
  await pres.writeFile({ fileName: pptPath });

  const fileUrl = `http://localhost:8003/public/uploads/${fileName}`;

  return {
    messages: [new AIMessage(`I have generated the PPT. You can download it here: ${fileUrl}`)],
    artifacts: [{
      id: "ppt-" + Date.now(),
      type: "presentation",
      title: "Generated PPT",
      files: [{ name: fileName, content: fileUrl }]
    }]
  };
};
